name: clang-tidy

on:
  pull_request:
    paths: ["**/*.cpp", "**/*.hpp", "**/*.h", ".clang-tidy", "cmake/**", "devenv/cmake/**"]
  push:
    branches: [main]
    paths: ["**/*.cpp", "**/*.hpp", "**/*.h", ".clang-tidy", "cmake/**", "devenv/cmake/**"]
  schedule:
    - cron: "17 4 * * 0"
  workflow_dispatch:

jobs:
  clang-tidy-own:
    name: own backend
    concurrency:
      group: clang-tidy-own-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    uses: devmarkusb/devenv/.github/workflows/clang-tidy-review.yml@main
    with:
      clang_image: ghcr.io/bemanproject/infra-containers-clang:latest
      setup_boost: true
      report_artifact_name: clang-tidy-full-project-report-own

  clang-tidy-qt:
    name: qt backend
    concurrency:
      group: clang-tidy-qt-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    uses: devmarkusb/devenv/.github/workflows/clang-tidy-review.yml@main
    with:
      clang_image: ghcr.io/bemanproject/infra-containers-clang:latest
      qt_version: '6.9.3'
      qt_install_deps: false
      extra_cmake_args: -DMB_UIWRAP_USE_IMPLEMENTATION=qt
      report_artifact_name: clang-tidy-full-project-report-qt
